### ISSUE TITLE
release ids related to restoration

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-data-release#5]
restoration curve set id
restoration mapping id

**Comment by ywkim312** [comment]
@vnarah2 @longshuicy Please add the new dataset id in here so I can embed those to PR

**Comment by longshuicy** [comment]
Earthquake Water Facility Restoration ids
Treatment plant: 61f07225903e515036cee0a0
Pumping plant: 61f072c6903e515036cee0a1
Well: 61f07362903e515036cee0a2
Water storage tank: 61f073e1903e515036cee0a3

-----
Earthquake Water Facility Restoration mapping id:
61f075bf903e515036cee0a4

**Comment by ywkim312** [comment]
@longshuicy  @nunezco2  are those ids on dev or prod? If it is dev, can someone migrate to prod and post ids in here?

**Comment by longshuicy** [comment]
> @longshuicy @nunezco2 are those ids on dev or prod? If it is dev, can someone migrate to prod and post ids in here?

It will be the same ids. But service change isn't deployed on production yet so we cannot migrate; if we migrate it will probably break....

**Comment by ywkim312** [comment]
if the ids are the same, then it should be okay. I will create PR

**Comment by vnarah2** [comment]
Earthquake water pipeline restorations:
Restoration curveset for class a,b,c: 61f2ed65903e515036cee0f3
Restoration curveset for class d,e,u: 61f2ed41903e515036cee0f2
Restoration mapping id: 61f35f09903e515036cee106

**Comment by ywkim312** [comment]
implemented
